<?php

namespace TunisiaMall\TunisiaMallBundle\Entity;

use Doctrine\ORM\EntityRepository;
use TunisiaMall\TunisiaMallBundle\Entity\CarteFidelite;



/**
 * CarteFidelite
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnseigneRepository extends EntityRepository
{
    public function search($idenseigne) {

        $query = $this->createQueryBuilder('TunisiaMallBundle:Media')
                ->select('a.id,a.nom,m.path')
                ->distinct()
                ->from('TunisiaMallBundle:Enseigne', 'a')
                
                ->join('a.image', 'm')
                
              
               
                ->where('a.iduser=:idenseigne')
                ->setParameter('idenseigne', $idenseigne);
                
        return $query->getQuery()->getResult();
    }
    public function modify($id,$nom)
    {
   $query=$this->getEntityManager()->createQuery("Update TunisiaMallBundle:Enseigne c SET c.nom=:nom where c.id=:id ");
      $query->setParameter('id',$id);
        $query->setParameter('nom',$nom);
         $query->execute();
    }
    public function supp($id)
    {
 $query=$this->getEntityManager()->createQuery("Delete from TunisiaMallBundle:Enseigne c where c.id=:id ");
        $query->setParameter('id',$id);
         $query->execute();

    }
}
