<?php
namespace TunisiaMall\TunisiaMallBundle\Entity;
use Doctrine\ORM\EntityRepository;
/**
 * visitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromotionRepository extends EntityRepository
{
     public function modify($id, $nom, $reduction,$dateDebut,$dateFin,$id_produit) {
        $query = $this->getEntityManager()
                ->createQuery("Update TunisiaMallBundle:Promotion p SET p.nom=:nom,p.reduction=:reduction,p.dateDebut=:dateDebut,p.dateFin=:dateFin,p.id_produit=:id_produit"
                               . " where p.id=:id ");
        $query->setParameter('id', $id);
        $query->setParameter('nom', $nom);
        $query->setParameter('reduction', $reduction);
                $query->setParameter('dateDebut', $dateDebut);
        $query->setParameter('dateFin', $dateFin);
                $query->setParameter('id_produit', $id_produit);


        $query->execute();
    }
     public function supp($id) {
        $query = $this->getEntityManager()->createQuery("Delete from TunisiaMallBundle:Publicite p where p.id=:id ");
        $query->setParameter('id', $id);
        
        
        $query->execute();
    }
     
}